// ────────────────────────────────────────────────────────────────────────────
// src/lib/promptUtils.ts
// Compose prompts for API calls. Uses English visualPrompt/motionPrompt
// directly (generated by AI). Sub-fields are Chinese for UI only.
// ────────────────────────────────────────────────────────────────────────────

import type { Shot } from "@/stores/projectStore";

/**
 * Return the visual prompt for API calls.
 * Always uses visualPrompt (English, generated by AI).
 * Sub-fields are Chinese for UI display only — never composed into API prompt.
 */
export function composeVisualPrompt(shot: Shot): string {
  // Use the English visualPrompt directly
  if (shot.visualPrompt?.trim()) {
    return shot.visualPrompt.trim();
  }
  // Fallback: compose from sub-fields (may be Chinese — not ideal but functional)
  const parts = [
    shot.subjectDesc,
    shot.sceneDesc,
    shot.detailDesc,
    shot.lightingDesc,
    shot.styleDesc,
  ]
    .map((s) => s?.trim())
    .filter(Boolean);

  if (parts.length > 0) return parts.join(", ");
  return shot.visualPrompt ?? "";
}

/**
 * Return the motion prompt for API calls.
 * Always uses motionPrompt (English, generated by AI).
 * Sub-fields are Chinese for UI display only — never composed into API prompt.
 */
export function composeMotionPrompt(shot: Shot): string {
  // Use the English motionPrompt directly
  if (shot.motionPrompt?.trim()) {
    return shot.motionPrompt.trim();
  }
  // Fallback: compose from sub-fields (may be Chinese — not ideal but functional)
  const parts = [
    shot.actionDesc,
    shot.cameraDesc,
    shot.envChangeDesc,
    shot.motionSpeedDesc,
  ]
    .map((s) => s?.trim())
    .filter(Boolean);

  if (parts.length > 0) return parts.join(", ");
  return shot.motionPrompt ?? "";
}
